import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Art Of Music",
  description: "Generated by Amit",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
